import { createAdminSupabaseClient } from "../../../../lib/supabase-admin";
import { readCourtActorManifestText } from "../../../../lib/court-actor-manifest-disk";
import { COURT_ACTOR_PUBLIC_THRESHOLD, actorLooseNameKey } from "../../../../lib/court-actors";
import { AliasResolver } from "../../../../lib/court-actor-similarity";
import {
  buildCourtActorBuckets,
  loadAliasResolver,
  loadFormDirectActorRows,
  loadHiddenSubmissionIds,
  loadRowReviewMap,
  type CourtActorBucketRow,
} from "../../../../lib/court-actor-buckets";
import { formatCourtActorLocationLabel } from "../../../../lib/court-actor-display";

import { withSupabaseReadTimeout } from "../../../../lib/supabase-timeout";
import { PUBLIC_REPORT_CACHE_HEADERS, PUBLIC_REPORT_FALLBACK_CACHE_HEADERS } from "../../../../lib/public-cache";
import { expirePublicActorCacheRows } from "../../../../lib/public-actor-cache";

const COURT_ACTORS_API_TIMEOUT_MS = 15_000;

/**
 * Spotlight manifest — generated by court-actor-posts/_scripts/deploy_actor_to_site.py
 * Maps `{state_abbr}/{slug}` to the deployed photo URL + share-page URL so the
 * API can hand the frontend the right links per actor card.
 */
type ManifestEntry = {
  slug: string;
  state_abbr: string | null;
  display_name: string | null;
  canonical_name: string | null;
  actor_bucket_key: string | null;
  photo_url: string | null;
  share_url: string | null;
};

/**
 * Manifest lookups by primary `state/slug` key, a fallback name-key map, AND
 * a per-state list used by the alias-cluster fallback.
 *
 * The two fallbacks exist because the manifest's slug + canonical_name are
 * frozen at deploy time (e.g. `naomi_catadeulla` / "Naomi Catadeulla") while
 * the public API derives both from the current canonical_name returned by the
 * active alias decision (e.g. "Naomi Cataudella" after a rename). Without a
 * fallback, photos for any actor whose canonical name has been respelled
 * after deploy would silently stop loading.
 *
 *   1) byStateLooseNameKey covers respellings that survive
 *      actorLooseNameKey() — casing, punctuation, titles, middle initials,
 *      repeated-letter slips.
 *   2) byState (used with the AliasResolver) covers transposed-letter or
 *      otherwise non-loose-equivalent renames, e.g. Catadeulla → Cataudella
 *      (loose keys `naomi catadeula` vs `naomi cataudela` differ but both
 *      live in the same alias cluster after the admin's same_actor decision).
 */
type ManifestLookups = {
  generatedAt: string | null;
  byStateSlug: Map<string, ManifestEntry>;
  byStateLooseNameKey: Map<string, ManifestEntry>;
  byState: Map<string, ManifestEntry[]>;
};

let _manifestCache: { mtime: number; lookups: ManifestLookups } | null = null;

function safeManifestEntry(entry: ManifestEntry): ManifestEntry {
  // The manifest is generated at deploy time and only contains actors whose
  // photo/share assets were actually written to disk. Trust the manifest URLs
  // without expensive HTTP existence checks, but still guard against malformed
  // or traversal paths.
  const safeUrl = (url: string | null | undefined): string | null => {
    const pathname = url?.trim();
    if (!pathname || !pathname.startsWith("/") || pathname.startsWith("//")) return null;
    if (!pathname.startsWith("/court-actors/")) return null;
    if (pathname.includes("/../") || pathname.endsWith("/..")) return null;
    return pathname;
  };
  return {
    ...entry,
    photo_url: safeUrl(entry.photo_url),
    share_url: safeUrl(entry.share_url),
  };
}

async function loadSpotlightManifest(): Promise<ManifestLookups> {
  try {
    const text = await readCourtActorManifestText();
    const cacheToken = text.length ^ (text.charCodeAt(0) ?? 0) ^ (text.charCodeAt(text.length - 1) ?? 0);
    if (_manifestCache && _manifestCache.mtime === cacheToken) {
      return _manifestCache.lookups;
    }
    const data = JSON.parse(text) as { generated_at?: unknown; actors?: ManifestEntry[] };
    const byStateSlug = new Map<string, ManifestEntry>();
    const byStateLooseNameKey = new Map<string, ManifestEntry>();
    const byState = new Map<string, ManifestEntry[]>();
    for (const rawEntry of data.actors || []) {
      const entry = safeManifestEntry(rawEntry);
      if (!entry.slug || !entry.state_abbr) continue;
      const state = entry.state_abbr.toLowerCase();
      byStateSlug.set(`${state}/${entry.slug}`, entry);
      for (const candidate of [entry.canonical_name, entry.display_name]) {
        if (!candidate) continue;
        const nk = actorLooseNameKey(candidate);
        if (!nk) continue;
        const key = `${state}|${nk}`;
        if (!byStateLooseNameKey.has(key)) {
          byStateLooseNameKey.set(key, entry);
        }
      }
      // Also index by actor_bucket_key's loose-name half, since the manifest
      // writer (deploy_actor_to_site.write_manifest) stamps the deploy-time
      // bucket key onto every entry. Catches cases where display_name and
      // canonical_name diverge from the bucket-key spelling.
      if (entry.actor_bucket_key) {
        const [bucketName] = entry.actor_bucket_key.split("|");
        const bucketNk = bucketName?.trim();
        if (bucketNk) {
          const key = `${state}|${bucketNk}`;
          if (!byStateLooseNameKey.has(key)) {
            byStateLooseNameKey.set(key, entry);
          }
        }
      }
      const list = byState.get(state) ?? [];
      list.push(entry);
      byState.set(state, list);
    }
    const generatedAt = typeof data.generated_at === "string" ? data.generated_at : null;
    const lookups = { generatedAt, byStateSlug, byStateLooseNameKey, byState };
    _manifestCache = { mtime: cacheToken, lookups };
    return lookups;
  } catch {
    return { generatedAt: null, byStateSlug: new Map(), byStateLooseNameKey: new Map(), byState: new Map() };
  }
}

function spotlightSlug(name: string): string {
  // Mirrors slugify() in court-actor-posts/_scripts/watch_new_actors.py.
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

function mergeManifestEntryAssetFallback(
  primary: ManifestEntry,
  fallback: ManifestEntry | null,
): ManifestEntry {
  if (!fallback) return primary;
  return {
    ...primary,
    photo_url: primary.photo_url ?? fallback.photo_url,
    share_url: primary.share_url ?? fallback.share_url,
  };
}

/**
 * Find the manifest entry for an actor card. Match precedence:
 *   1. strict `state/slug` (covers the common case — no rename since deploy)
 *   2. state + loose-name-key (covers casing, punctuation, title prefix,
 *      middle initial, and repeated-letter respellings)
 *   3. alias cluster match (covers transposed-letter or otherwise
 *      non-loose-equivalent renames where the admin used the Possible
 *      Matches UI to merge two spellings into one canonical actor)
 *
 * locationKey is passed through in its original case (typically uppercase
 * like "KS") so the AliasResolver lookup uses the same key the alias
 * decisions table was written with.
 */
function findManifestEntry(
  lookups: ManifestLookups,
  locationKey: string,
  displayName: string,
  aliasResolver: AliasResolver | null,
): ManifestEntry | null {
  const stateLower = locationKey.toLowerCase();
  if (!stateLower) return null;
  const slug = spotlightSlug(displayName);
  const nk = actorLooseNameKey(displayName);
  if (slug) {
    const hit = lookups.byStateSlug.get(`${stateLower}/${slug}`);
    if (hit) {
      const looseFallback = nk ? lookups.byStateLooseNameKey.get(`${stateLower}|${nk}`) ?? null : null;
      return mergeManifestEntryAssetFallback(hit, looseFallback);
    }
  }
  if (nk) {
    const hit = lookups.byStateLooseNameKey.get(`${stateLower}|${nk}`);
    if (hit) return hit;
  }
  if (!aliasResolver) return null;

  // Alias-cluster fallback. The API's displayName is the alias-resolved
  // canonical (post-rename); the manifest entry was deployed under the
  // pre-rename spelling. If both spellings belong to the same same_actor
  // cluster, the resolver's cluster_key on either side will match.
  const apiResolution = aliasResolver.resolve(displayName, locationKey);
  if (!apiResolution) return null;
  const stateEntries = lookups.byState.get(stateLower) ?? [];
  for (const entry of stateEntries) {
    // Match when the entry's bucket-key loose name IS the canonical key —
    // i.e. the entry was deployed under the now-canonical spelling.
    if (entry.actor_bucket_key) {
      const [bucketName] = entry.actor_bucket_key.split("|");
      if (bucketName?.trim() === apiResolution.canonical_name_key) return entry;
    }
    // Otherwise resolve the entry's own deploy-time name and compare
    // clusters. Same cluster_key → same actor under a different spelling.
    const candidateName = entry.canonical_name || entry.display_name;
    if (!candidateName) continue;
    const entryResolution = aliasResolver.resolve(candidateName, locationKey);
    if (entryResolution && entryResolution.cluster_key === apiResolution.cluster_key) {
      return entry;
    }
  }
  return null;
}

type AdminClient = ReturnType<typeof createAdminSupabaseClient>;

// Public, no-PII court-actor data — safe to serve from the edge cache so the
// dashboard doesn't re-query Supabase on every visit. See lib/public-cache.ts.
export const maxDuration = 60;

const PUBLIC_ACTORS_CACHE_HEADERS = PUBLIC_REPORT_CACHE_HEADERS;
const STATIC_ACTORS_WARNING =
  "Live court actor data is temporarily unavailable; showing the latest generated public snapshot.";

/**
 * Returns court actors named by enough different families to cross the
 * shared auto-publish threshold. Names are matched conservatively on normalized name +
 * location_key, so casing, punctuation, common titles, middle initials,
 * repeated-letter misspellings, and different role labels do not split the
 * same person. Families are deduped by email + location, so one family naming
 * the same person twice still only counts once.
 *
 * The actual row-loading + alias + family-bucketing now lives in
 * lib/court-actor-buckets.ts so the public registry and the Connection Circles
 * matching layer count families IDENTICALLY. This route adds public-only
 * concerns on top: the 3-family threshold, manifest photo/share lookup, the
 * default sort, and the 5-minute row cache.
 *
 * Never exposes: notes, submission_id, reporter identity.
 *
 * Query params:
 *   - state (optional) — Legacy US state code, filters to that location only.
 *   - location (optional) — Location key, filters to that location only.
 *
 * Response:
 *   { actors: [{ role, name, court_or_county?, state_code, location_key, count }] }
 */

let formDirectRowsCache:
  | { expiresAt: number; promise: Promise<CourtActorBucketRow[]> }
  | null = null;

// Cache the fully-computed public actor list (after bucketing + manifest lookup)
// for 10 minutes. Keyed by location filter or "all". This is much heavier than
// the raw row read, so caching it saves significant CPU on every request.
type PublicActorsCacheEntry = {
  expiresAt: number;
  promise: Promise<PublicActor[]>;
};
const publicActorsCache = new Map<string, PublicActorsCacheEntry>();
const PUBLIC_ACTORS_CACHE_TTL_MS = 10 * 60 * 1000;
const PUBLIC_ACTORS_CACHE_VERSION = "v3";
const PUBLIC_ACTORS_MANIFEST_CACHE_KEY = "__manifest__";

type PublicActor = {
  role: string;
  name: string;
  court_or_county: string | null;
  state_code: string | null;
  location_key: string | null;
  count: number;
  submission_count: number;
  latest_reported_at: string | null;
  photo_url: string | null;
  share_url: string | null;
};

function dbPublicActorsCacheKey(cacheKey: string): string {
  return `${PUBLIC_ACTORS_CACHE_VERSION}:${cacheKey}`;
}

// Cache the paginated form_direct read for 5 minutes. The canonical loader
// lives in lib/court-actor-buckets.ts; this wrapper only adds the route-local
// cache so the public report doesn't re-page Supabase on every visit.
async function loadCachedFormDirectActorRows(sb: AdminClient): Promise<CourtActorBucketRow[]> {
  const now = Date.now();
  if (formDirectRowsCache && formDirectRowsCache.expiresAt > now) {
    return formDirectRowsCache.promise;
  }

  const promise = loadFormDirectActorRows(sb);
  formDirectRowsCache = {
    expiresAt: now + 5 * 60 * 1000,
    promise,
  };

  try {
    return await promise;
  } catch (error) {
    if (formDirectRowsCache?.promise === promise) {
      formDirectRowsCache = null;
    }
    throw error;
  }
}

async function loadDbPublicActorCache(
  sb: AdminClient,
  cacheKey: string,
  maxAgeMs = 0,
): Promise<{ actors: PublicActor[]; expired: boolean } | null> {
  try {
    const minExpiresAt = new Date(Date.now() - maxAgeMs).toISOString();
    const dbCacheKey = dbPublicActorsCacheKey(cacheKey);
    const { data, error } = await sb
      .from("public_actor_cache")
      .select("payload, expires_at")
      .eq("cache_key", dbCacheKey)
      .gt("expires_at", minExpiresAt)
      .order("expires_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (error) {
      if (error.code === "42P01" || error.code === "PGRST205") return null;
      console.error("public_actor_cache read error:", error.message);
      return null;
    }
    if (data?.payload && Array.isArray(data.payload)) {
      const rowExpiresAt = data.expires_at ? new Date(data.expires_at).getTime() : 0;
      const rowExpired = !rowExpiresAt || rowExpiresAt <= Date.now();
      if (rowExpired && maxAgeMs === 0) return null;

      const manifestCurrent = await isDbPublicActorCacheManifestCurrent(sb);
      // Serve a still-valid actor cache even when manifest meta lags a deploy.
      // Photo/share URLs are re-merged from the on-disk manifest on recompute;
      // rejecting the whole list here made /report go blank during refresh windows.
      const expired = rowExpired || !manifestCurrent;
      return { actors: data.payload as PublicActor[], expired };
    }
  } catch (err) {
    console.error("loadDbPublicActorCache error:", err);
  }
  return null;
}

function parseManifestGeneratedAt(value: unknown): number | null {
  if (typeof value !== "string" || !value.trim()) return null;
  const time = Date.parse(value);
  return Number.isFinite(time) ? time : null;
}

async function isDbPublicActorCacheManifestCurrent(sb: AdminClient): Promise<boolean> {
  try {
    const localManifest = await loadSpotlightManifest();
    const localGeneratedAt = parseManifestGeneratedAt(localManifest.generatedAt);
    if (localGeneratedAt === null) return true;

    const { data, error } = await sb
      .from("public_actor_cache")
      .select("payload")
      .eq("cache_key", PUBLIC_ACTORS_MANIFEST_CACHE_KEY)
      .maybeSingle();
    if (error) {
      if (error.code === "42P01" || error.code === "PGRST205") return true;
      console.error("public_actor_cache manifest meta read error:", error.message);
      return true;
    }

    const payload = data?.payload && typeof data.payload === "object" && !Array.isArray(data.payload)
      ? data.payload as { generated_at?: unknown }
      : null;
    const cachedGeneratedAt = parseManifestGeneratedAt(payload?.generated_at);
    if (cachedGeneratedAt === null) return true;
    return cachedGeneratedAt >= localGeneratedAt;
  } catch (err) {
    console.error("isDbPublicActorCacheManifestCurrent error:", err);
    return true;
  }
}

async function maybeRefreshMaterializedView(sb: AdminClient): Promise<void> {
  try {
    const { data, error } = await sb
      .from("mv_refresh_log")
      .select("refreshed_at")
      .eq("view_name", "mv_court_actors_public_safe")
      .maybeSingle();
    if (error) return;
    const refreshedAt = data?.refreshed_at ? new Date(data.refreshed_at).getTime() : 0;
    const stale = Date.now() - refreshedAt > 10 * 60 * 1000;
    if (stale) {
      // Fire-and-forget: refresh the MV in the background so the current
      // request is not blocked. Subsequent requests get the refreshed data.
      Promise.resolve(sb.rpc("refresh_mv_court_actors_public_safe"))
        .then(() => console.log("Refreshed mv_court_actors_public_safe"))
        .catch(err => console.error("MV refresh failed:", err));
    }
  } catch (err) {
    console.error("maybeRefreshMaterializedView error:", err);
  }
}

async function saveDbPublicActorCache(
  sb: AdminClient,
  cacheKey: string,
  actors: PublicActor[],
  ttlMs: number,
): Promise<void> {
  try {
    const expiresAt = new Date(Date.now() + ttlMs).toISOString();
    const manifest = await loadSpotlightManifest();
    const dbCacheKey = dbPublicActorsCacheKey(cacheKey);
    await sb
      .from("public_actor_cache")
      .upsert([
        { cache_key: dbCacheKey, payload: actors as unknown as Record<string, unknown>, expires_at: expiresAt },
        {
          cache_key: PUBLIC_ACTORS_MANIFEST_CACHE_KEY,
          payload: { generated_at: manifest.generatedAt },
          expires_at: expiresAt,
        },
      ], { onConflict: "cache_key" });
  } catch (err) {
    console.error("saveDbPublicActorCache error:", err);
  }
}

type ComputePublicActorsOptions = {
  // Internal callers (e.g. the cache-warming cron) can afford to wait longer
  // and skip the manifest asset existence checks because the manifest is only
  // written after assets are actually generated.
  readTimeoutMs?: number;
  bypassRowCache?: boolean;
};

export async function computePublicActorsDirect(
  sb: AdminClient,
  stateFilter: string | null,
  locationFilter: string | null,
  opts?: ComputePublicActorsOptions,
): Promise<PublicActor[]> {
  const readTimeoutMs = opts?.readTimeoutMs ?? 10_000;
  const actorRowsPromise = opts?.bypassRowCache ? loadFormDirectActorRows(sb) : loadCachedFormDirectActorRows(sb);
  const [all, rowReviewMap, hiddenSubmissionIds, aliasResolver] = await Promise.all([
    withSupabaseReadTimeout(actorRowsPromise, "public court actor rows", readTimeoutMs),
    withSupabaseReadTimeout(loadRowReviewMap(sb), "court actor row review map", 5000),
    withSupabaseReadTimeout(loadHiddenSubmissionIds(sb), "hidden submission ids", 5000),
    withSupabaseReadTimeout(loadAliasResolver(sb), "court actor alias decisions", 5000),
  ]);

  const filteredRows = (stateFilter || locationFilter)
    ? all.filter(row => {
        const location = row.location_key?.trim() || row.state_code?.trim().toUpperCase() || null;
        if (!location) return false;
        if (stateFilter && location !== stateFilter) return false;
        if (locationFilter && location !== locationFilter) return false;
        return true;
      })
    : all;

  const buckets = buildCourtActorBuckets({
    rows: filteredRows,
    reviewMap: rowReviewMap,
    hiddenSubmissionIds,
    aliasResolver,
  });

  const manifest = await loadSpotlightManifest();

  return Array.from(buckets.values())
    .filter(b => b.families.size >= COURT_ACTOR_PUBLIC_THRESHOLD)
    .map(b => {
      const displayName = b.displayName;
      const locationKey = b.location_key || b.state_code || "";
      const manifestEntry = findManifestEntry(manifest, locationKey, displayName, aliasResolver);
      return {
        role: b.roleSummary,
        name: displayName,
        court_or_county: formatCourtActorLocationLabel(b.court_or_county),
        state_code: b.state_code,
        location_key: b.location_key,
        count: b.families.size,
        submission_count: b.submissionIds.size,
        latest_reported_at: b.latest_reported_at,
        photo_url: manifestEntry?.photo_url ?? null,
        share_url: manifestEntry?.share_url ?? null,
      };
    })
    .sort((a, b) => {
      const newest = (b.latest_reported_at ?? "").localeCompare(a.latest_reported_at ?? "");
      return newest || b.count - a.count || a.name.localeCompare(b.name);
    });
}

export async function refreshPublicActorCache(
  sb: AdminClient,
  opts?: { readTimeoutMs?: number; ttlMs?: number },
): Promise<PublicActor[]> {
  try {
    await sb.rpc("refresh_mv_court_actors_public_safe");
  } catch (err) {
    console.error("refreshPublicActorCache MV refresh failed:", err);
  }

  formDirectRowsCache = null;
  const actors = await computePublicActorsDirect(sb, null, null, {
    readTimeoutMs: opts?.readTimeoutMs ?? 55_000,
    bypassRowCache: true,
  });
  const ttlMs = opts?.ttlMs ?? 60 * 60 * 1000;
  const expiresAt = new Date(Date.now() + ttlMs).toISOString();
  const promise = Promise.resolve(actors);
  const manifest = await loadSpotlightManifest();
  const dbCacheKey = dbPublicActorsCacheKey("all");
  publicActorsCache.set("all", { expiresAt: Date.now() + ttlMs, promise });
  await sb
    .from("public_actor_cache")
    .upsert([
      { cache_key: dbCacheKey, payload: actors as unknown as Record<string, unknown>, expires_at: expiresAt },
      {
        cache_key: PUBLIC_ACTORS_MANIFEST_CACHE_KEY,
        payload: { generated_at: manifest.generatedAt },
        expires_at: expiresAt,
      },
    ], { onConflict: "cache_key" });
  return actors;
}

export async function expirePublicActorCache(sb: AdminClient): Promise<void> {
  formDirectRowsCache = null;
  publicActorsCache.clear();
  await expirePublicActorCacheRows(sb);
}

async function computeAndSavePublicActors(
  sb: AdminClient,
  stateFilter: string | null,
  locationFilter: string | null,
): Promise<PublicActor[]> {
  const cacheKey = stateFilter || locationFilter || "all";
  const actors = await computePublicActorsDirect(sb, stateFilter, locationFilter);
  const promise = Promise.resolve(actors);
  publicActorsCache.set(cacheKey, { expiresAt: Date.now() + PUBLIC_ACTORS_CACHE_TTL_MS, promise });
  saveDbPublicActorCache(sb, cacheKey, actors, PUBLIC_ACTORS_CACHE_TTL_MS).catch(() => undefined);
  return actors;
}

type ComputeResult = {
  actors: PublicActor[];
  stale: boolean;
};

function actorLocation(actor: PublicActor): string | null {
  return actor.location_key?.trim() || actor.state_code?.trim().toUpperCase() || null;
}

function filterActorsByLocation(
  actors: PublicActor[],
  stateFilter: string | null,
  locationFilter: string | null,
): PublicActor[] {
  if (!stateFilter && !locationFilter) return actors;
  return actors.filter(actor => {
    const location = actorLocation(actor);
    if (!location) return false;
    if (stateFilter && location !== stateFilter) return false;
    if (locationFilter && location !== locationFilter) return false;
    return true;
  });
}

async function computePublicActors(
  sb: AdminClient,
  stateFilter: string | null,
  locationFilter: string | null,
): Promise<ComputeResult | null> {
  const cacheKey = stateFilter || locationFilter || "all";
  const allCacheKey = "all";
  const now = Date.now();

  const memoryCached = publicActorsCache.get(cacheKey);
  if (memoryCached && memoryCached.expiresAt > now) {
    return { actors: await memoryCached.promise, stale: false };
  }

  // Prefer a fresh cache for the exact filter, then fall back to the global list.
  const freshSpecific = await loadDbPublicActorCache(sb, cacheKey, 0);
  const freshAll = cacheKey !== allCacheKey ? await loadDbPublicActorCache(sb, allCacheKey, 0) : null;
  const freshDb = freshSpecific ?? freshAll;
  if (freshDb) {
    const actors = filterActorsByLocation(freshDb.actors, stateFilter, locationFilter);
    const promise = Promise.resolve(actors);
    publicActorsCache.set(cacheKey, { expiresAt: now + PUBLIC_ACTORS_CACHE_TTL_MS, promise });
    return { actors, stale: freshDb.expired };
  }

  try {
    const actors = await computeAndSavePublicActors(sb, stateFilter, locationFilter);
    return { actors, stale: false };
  } catch (err) {
    console.error("public court actor live recompute failed:", err);
  }

  // Stale cache (up to 24 hours old) is still useful if a live recompute fails.
  const staleSpecific = await loadDbPublicActorCache(sb, cacheKey, 24 * 60 * 60 * 1000);
  const staleAll = cacheKey !== allCacheKey ? await loadDbPublicActorCache(sb, allCacheKey, 24 * 60 * 60 * 1000) : null;
  const staleDb = staleSpecific ?? staleAll;
  if (staleDb) {
    const actors = filterActorsByLocation(staleDb.actors, stateFilter, locationFilter);
    const promise = Promise.resolve(actors);
    publicActorsCache.set(cacheKey, { expiresAt: now + PUBLIC_ACTORS_CACHE_TTL_MS, promise });
    return { actors, stale: true };
  }

  // No cache available. The caller should fall back to the manifest snapshot
  // and let the cron (or a manual refresh) populate the cache.
  return null;
}

async function staticPublicActorsResponse(
  locationFilter: string | null,
  limit: number,
  offset: number,
  countsOnly: boolean,
  warning = STATIC_ACTORS_WARNING,
) {
  const actors = await loadManifestPublicActorsSnapshot(locationFilter);
  const total = actors.length;

  if (countsOnly) {
    const counts: Record<string, number> = {};
    for (const actor of actors) {
      const location = actor.location_key || actor.state_code;
      if (!location) continue;
      counts[location] = (counts[location] ?? 0) + 1;
    }
    return Response.json(
      { counts, total, threshold: COURT_ACTOR_PUBLIC_THRESHOLD, warning, data_mode: "snapshot" },
      { headers: PUBLIC_REPORT_FALLBACK_CACHE_HEADERS },
    );
  }

  const page = actors.slice(offset, offset + limit);
  return Response.json(
    {
      actors: page,
      total,
      threshold: COURT_ACTOR_PUBLIC_THRESHOLD,
      pagination: { limit, offset, has_more: offset + page.length < total },
      warning,
      data_mode: "snapshot",
    },
    { headers: PUBLIC_REPORT_FALLBACK_CACHE_HEADERS },
  );
}

function safeManifestAssetUrl(assetUrl: string | null | undefined): string | null {
  const url = assetUrl?.trim();
  if (!url || !url.startsWith("/") || url.startsWith("//")) return null;
  const pathname = url.split(/[?#]/, 1)[0];
  if (!pathname.startsWith("/court-actors/")) return null;
  if (pathname.includes("/../") || pathname.endsWith("/..")) return null;
  return pathname;
}

async function loadManifestPublicActorsSnapshot(locationFilter: string | null) {
  const normalizedLocation = locationFilter?.trim().toUpperCase() || null;
  const manifest = await loadSpotlightManifest();
  const actors = Array.from(manifest.byStateSlug.values())
    .filter(entry => {
      const state = entry.state_abbr?.trim().toUpperCase() || null;
      return Boolean(state && (!normalizedLocation || state === normalizedLocation));
    })
    .map(entry => {
      const state = entry.state_abbr?.trim().toUpperCase() || null;
      return {
        role: "Court Actor",
        name: entry.display_name || entry.canonical_name || entry.slug.replace(/_/g, " "),
        court_or_county: null,
        state_code: state,
        location_key: state,
        count: COURT_ACTOR_PUBLIC_THRESHOLD,
        submission_count: COURT_ACTOR_PUBLIC_THRESHOLD,
        latest_reported_at: null,
        photo_url: safeManifestAssetUrl(entry.photo_url),
        share_url: safeManifestAssetUrl(entry.share_url),
      };
    });
  return actors.sort((a, b) => (a.state_code ?? "").localeCompare(b.state_code ?? "") || a.name.localeCompare(b.name));
}

export async function GET(request: Request) {
  let fallbackLocationFilter: string | null = null;
  let limit = 1000;
  let offset = 0;
  let countsOnly = false;
  try {
    const { searchParams } = new URL(request.url);
    const stateFilter = searchParams.get("state")?.trim().toUpperCase() || null;
    const locationFilter = searchParams.get("location")?.trim() || null;
    fallbackLocationFilter = locationFilter || stateFilter;
    limit = Math.min(parseInt(searchParams.get("limit") ?? "", 10) || 1000, 1000);
    offset = Math.max(parseInt(searchParams.get("offset") ?? "", 10) || 0, 0);
    countsOnly = searchParams.get("counts_only") === "1";

    const sb = createAdminSupabaseClient();

    // Keep the materialized view reasonably fresh without blocking the request.
    maybeRefreshMaterializedView(sb);

    const cached = await withSupabaseReadTimeout(
      computePublicActors(sb, stateFilter, locationFilter),
      "public court actor cache read",
      COURT_ACTORS_API_TIMEOUT_MS,
    );

    if (!cached) {
      // Cache is empty (e.g. right after a deploy before the cron has warmed it).
      // Serve the generated manifest snapshot so the page is never blank.
      return staticPublicActorsResponse(
        fallbackLocationFilter,
        limit,
        offset,
        countsOnly,
        "Court actor cache is still warming; showing the latest generated snapshot.",
      );
    }

    const publicActors = cached.actors;
    const stale = cached.stale;

    const total = publicActors.length;
    const staleWarning = stale
      ? "Court actor data is refreshing in the background; showing the most recent cached list."
      : null;

    if (countsOnly) {
      const counts: Record<string, number> = {};
      for (const actor of publicActors) {
        const location = actor.location_key || actor.state_code;
        if (!location) continue;
        counts[location] = (counts[location] ?? 0) + 1;
      }
      return Response.json(
        { counts, total, threshold: COURT_ACTOR_PUBLIC_THRESHOLD, warning: staleWarning, data_mode: stale ? "cached" : "live" },
        { headers: PUBLIC_ACTORS_CACHE_HEADERS },
      );
    }

    const page = publicActors.slice(offset, offset + limit);

    return Response.json(
      {
        actors: page,
        total,
        threshold: COURT_ACTOR_PUBLIC_THRESHOLD,
        pagination: { limit, offset, has_more: offset + page.length < total },
        warning: staleWarning,
        data_mode: stale ? "cached" : "live",
      },
      { headers: PUBLIC_ACTORS_CACHE_HEADERS },
    );
  } catch (err) {
    console.error("GET /api/survey/court-actors error:", err);
    return staticPublicActorsResponse(fallbackLocationFilter, limit, offset, countsOnly);
  }
}
