/**
 * Syncs state_resource_links in Supabase with the PDFs that actually exist
 * in outputs/state_packets_pdf/.
 *
 * Reads state_packets_pdf/index.json, which is generated by agent.py option 16.
 * For each state in that index:
 *   - drive_folder_url → /state-reports/XX.pdf   (served from website/public via symlink)
 *   - report_available → true
 *   - report_title     → "XX Family Rights Report"
 *
 * States NOT in the index (no PDF yet) are flipped back to report_available=false
 * so stale links don't point at missing files.
 *
 * Run:  npx tsx --env-file=.env.local scripts/sync-state-reports.ts
 */

import { createClient } from "@supabase/supabase-js";
import { readFileSync, existsSync } from "fs";

const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

const INDEX_PATH = "/Volumes/2023 Big 18/standwithmeg/outputs/state_packets_pdf/index.json";

type PacketIndex = {
  state: string;
  submissions: number;
  file: string;
  size_kb: number;
};

async function main() {
  if (!existsSync(INDEX_PATH)) {
    console.error(`Missing index file: ${INDEX_PATH}`);
    console.error("Run agent.py option 16 first to generate the PDFs + index.");
    process.exit(1);
  }

  const index: PacketIndex[] = JSON.parse(readFileSync(INDEX_PATH, "utf8"));
  const withPdf = new Set(index.map(r => r.state.toUpperCase()));
  console.log(`Found ${index.length} state PDFs in index.json.`);

  // For each state with a PDF, update the row
  let updated = 0;
  for (const rec of index) {
    const code = rec.state.toUpperCase();
    const pdfUrl = `/state-reports/${code}.pdf`;

    const { error } = await sb.from("state_resource_links")
      .update({
        drive_folder_url: pdfUrl,
        report_available: true,
        report_title: `${code} Family Rights Report`,
        updated_at: new Date().toISOString(),
      })
      .eq("state_code", code);

    if (error) {
      console.error(`  Error updating ${code}:`, error.message);
    } else {
      updated++;
    }
  }

  // States without a PDF — flip report_available back to false
  const { data: allStates } = await sb.from("state_resource_links").select("state_code");
  const missing = (allStates ?? [])
    .map(r => r.state_code.toUpperCase())
    .filter(code => !withPdf.has(code));

  if (missing.length > 0) {
    const { error } = await sb.from("state_resource_links")
      .update({ report_available: false, updated_at: new Date().toISOString() })
      .in("state_code", missing);
    if (error) console.error("Error un-flagging missing states:", error.message);
  }

  console.log(`Updated ${updated} states with PDFs.`);
  console.log(`Marked ${missing.length} states without PDFs as report_available=false.`);
  console.log(`\nStates with reports: ${[...withPdf].sort().join(", ")}`);
}

main().catch(err => { console.error(err); process.exit(1); });
